### register

POST {{baseUrl}}/register
Content-Type: application/json

{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "username": "{{username}}{{$random.integer(100)}}",
  "email": "{{username}}{{$random.integer(100)}}@gmail.com",
  "password": "{{password}}",
  "browserId": "{{browserId}}",
  "deviceId": "{{deviceId}}"
}

> {%
  client.test('Check response status', () => {
    client.assert(response.status === 201, 'Response status is not 201');
  })

  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken)
%}

### login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}88",
  "password":"{{password}}",
  "browserId": "{{browserId}}",
  "deviceId": "{{deviceId}}"
}

> {%
  client.test('Check response status', () => {
    client.assert(response.status === 200, 'Response status is not 200');
  })

  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
  client.log(client.global.get('refreshToken'));
%}

### refresh
GET {{baseUrl}}/refresh-token
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

> {%

  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken)
  client.log(client.global.get('refreshToken'));
%}

### read users
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}



